import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUrl,
  Matches,
  MaxLength,
  MinLength,
} from 'class-validator';
import { Trim } from '../../../common/decorators/trim.decorator';

/**
 * Field rules follow FRD §9.2 (Steps 4-5): legal name, business type,
 * registration number, registered address and sector are mandatory; trade
 * name, website and an additional contact person are optional.
 *
 * Business type and registration number are deliberately free text with only
 * length limits — the exact registration format (Udyam / CIN / other) is a
 * TO-BE-VALIDATED item (FRD §37), so hard-coding a pattern or an enum here
 * would silently commit to an unconfirmed government standard.
 *
 * `ownerUserId` and `referenceNumber` are intentionally absent: ownership is
 * always the authenticated caller, and the reference number is generated by
 * the database. With `forbidNonWhitelisted`, sending either is a 400.
 */
export class CreateEnterpriseDto {
  @ApiProperty({ example: 'Sahyadri Precision Components Pvt Ltd' })
  @Trim()
  @IsString()
  @MinLength(2)
  @MaxLength(200)
  name: string;

  @ApiProperty({
    example: 'Private Limited Company',
    description:
      'Proprietorship / Partnership / Pvt Ltd / LLP / etc. Free text (format not yet fixed by the department).',
  })
  @Trim()
  @IsString()
  @MinLength(2)
  @MaxLength(100)
  businessType: string;

  @ApiProperty({ example: 'UDYAM-MH-26-0012345' })
  @Trim()
  @IsString()
  @MinLength(3)
  @MaxLength(50)
  registrationNumber: string;

  @ApiProperty({
    example: 'UDYAM',
    description:
      'Which registry the number belongs to (Udyam, CIN, ...). Free text — the accepted set is still to be validated with the department.',
  })
  @Trim()
  @IsString()
  @MinLength(2)
  @MaxLength(30)
  registrationNumberType: string;

  @ApiProperty({ example: 'Plot 14, MIDC Chakan, Pune, Maharashtra 410501' })
  @Trim()
  @IsString()
  @MinLength(5)
  @MaxLength(500)
  address: string;

  @ApiProperty({ example: 'Engineering & Auto Components' })
  @Trim()
  @IsString()
  @MinLength(2)
  @MaxLength(100)
  sector: string;

  @ApiPropertyOptional({ example: 'Sahyadri Precision' })
  @IsOptional()
  @Trim()
  @IsString()
  @IsNotEmpty()
  @MaxLength(200)
  tradeName?: string;

  @ApiPropertyOptional({ example: 'https://sahyadri-precision.example.com' })
  @IsOptional()
  @Trim()
  @IsUrl({ protocols: ['http', 'https'], require_protocol: true })
  @MaxLength(300)
  website?: string;

  @ApiPropertyOptional({ example: 'Meera Kulkarni' })
  @IsOptional()
  @Trim()
  @IsString()
  @IsNotEmpty()
  @MaxLength(150)
  contactPersonName?: string;

  @ApiPropertyOptional({ example: '9123456780' })
  @IsOptional()
  @Trim()
  @Matches(/^[0-9]{10,15}$/, { message: 'mobile must be 10 to 15 digits' })
  contactPersonMobile?: string;
}
